# Generated by Django 2.2.5 on 2019-10-04 07:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_image_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicinal_Trees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(unique=True, upload_to='trees/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
