from django.conf.urls import url
from .views import (IndexView, DirectorMessageView, VisionAndMissionView, EstablishmentView, StructureView, SyllabusView,
                    SyllabusView, BookAndAuthors_level1_View,BookAndAuthors_level2_View, UnitWiseNotes_level1_View,UnitWiseNotes_level2_View ,
                    VideoLectures_level1_View,VideoLectures_level2_View, UnitWisePPT_level1_View, UnitWisePPT_level2_View, UTQuestionPaper_level1_View,
                    UTQuestionPaper_level2_View,
                    FDPView, StudentsWorkshopView, EventsView, ClubsView,
                    ImpactStudentView, ImpactFacultyView, SaveContactView,Developer_View,Nature_Club_About,
                    Nature_Club_Activity, Health_Club_About, Health_Club_Activity, Event_Page,
                    Sharing_Of_FacultyMembers,Sharing_Of_Students,AluminiSharing)
                    

urlpatterns = [
    url(r'^director-message/$', DirectorMessageView.as_view(), name='director-message'),
    url(r'^vision-and-mission/$', VisionAndMissionView.as_view(), name='vision-and-mission'),
    url(r'^establishment/$', EstablishmentView.as_view(), name='establishment'),
    url(r'^structure/$', StructureView.as_view(), name='structure'),
    url(r'^syllabus/$', SyllabusView.as_view(), name='syllabus'),
    url(r'^book-and-authors-level1/$', BookAndAuthors_level1_View.as_view(), name='book-and-authors-level1'),
    url(r'^book-and-authors-level2/$', BookAndAuthors_level2_View.as_view(), name='book-and-authors-level2'),
    url(r'^unit-wise-notes-level1/$', UnitWiseNotes_level1_View.as_view(), name='unit-wise-notes-level1'),
    url(r'^unit-wise-notes-level2/$', UnitWiseNotes_level2_View.as_view(), name='unit-wise-notes-level2'),
    url(r'^video-lectures-level1/$', VideoLectures_level1_View.as_view(), name='video-lectures-level1'),
    url(r'^video-lectures-level2/$', VideoLectures_level2_View.as_view(), name='video-lectures-level2'),
    url(r'^unit-wise-ppt-level1/$', UnitWisePPT_level1_View.as_view(), name='unit-wise-ppt-level1'),
    url(r'^unit-wise-ppt-level2/$', UnitWisePPT_level2_View.as_view(), name='unit-wise-ppt-level2'),
    url(r'^UT-question-paper-level1/$', UTQuestionPaper_level1_View.as_view(), name='UT-question-paper-level1'),
    url(r'^UT-question-paper-level2/$', UTQuestionPaper_level2_View.as_view(), name='UT-question-paper-level2'),
    # url(r'^previous-paper/$', PreviousPaperView.as_view(), name='previous-paper'),
    url(r'^fdps/$', FDPView.as_view(), name='fdps'),
    url(r'^students-workshop/$', StudentsWorkshopView.as_view(), name='students-workshop'),
    url(r'^events/$', EventsView.as_view(), name='events'),
    url(r'^clubs/$', ClubsView.as_view(), name='clubs'),
    url(r'^impact-student/$', ImpactStudentView.as_view(), name='impact-student'),
    url(r'^impact-faculty/$', ImpactFacultyView.as_view(), name='impact-faculty'),
    url(r'^savecontact$', SaveContactView.as_view(), name='save_contact'),
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^developer/$',Developer_View.as_view() ,name ='developer'),
    url(r'^club_about/$', Nature_Club_About.as_view(), name='club_about'),
    url(r'^club_activity/$', Nature_Club_Activity.as_view(), name='club_activity'),
    url(r'^health_about/$', Health_Club_About.as_view(), name='health_about'),
    url(r'^health_activity/$', Health_Club_Activity.as_view(), name='health_activity'),
    url(r'^event/(?P<id>[0-9]+)/$', Event_Page.as_view(), name='event_page'),
    url(r'^sharing_students/$', Sharing_Of_Students.as_view(), name='sharing_students'),
    url(r'^sharing_facultymember/$', Sharing_Of_FacultyMembers.as_view(), name='sharing_facultymember'),
    url(r'^event/$', Event_Page.as_view(), name='event'),
    url(r'^alumni-sharing/$', AluminiSharing.as_view(), name='alumni-sharing'),
    # url(r'^medicinal-trees/$',Trees_medicinal.as_view(),name ='medicinal-trees'),
    # url(r'^tree-description/$',Tree_Description.as_view(),name ='tree-description'),

]

